MAIN = case_0.cpp
SOURCE = ../../sources/convex2D.cpp
HEAD = ../../headers/convex2D.h
CPPC = g++

run: $(MAIN) $(SOURCE) $(HEAD)
	$(CPPC) $(MAIN) $(SOURCE) -o run

clean:
	$(RM) *~

resetf: clean
	rm -f run *bor point* *er domain_boundary